version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez data raw
    tables:
      - name: sales
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        identifier: raw_gz_sales
        description: table des ventes
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
        tests:
          - unique:
              column_name: "(orders_id ||'-'|| pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: table des produits
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
          - name: purchase_price
      - name: ship
        identifier: raw_gz_ship
        description: table des envois
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
          - name: shipping_fee
          - name: log_cost
          - name: ship_cost

models:
  - name: int_sales_margin
    columns:
      - name: orders_id
      - name: date_date
      - name: revenue
      - name: quantity
      - name: purchase_cost
        description: round((p.purchase_price*s.quantity),2)
      - name: margin
        description: round (s.revenue - (p.purchase_price*s.quantity),2)
  - name: int_orders_margin
    columns:
      - name: orders_id
        description: primary key of the table
        tests:
              - unique
      - name: date_date
      - name: revenue
        description: round (sum (revenue),2)
      - name: quantity
        description: round (sum (quantity),2)
      - name: purchase_cost
        description: round (sum (purchase_cost),2)
      - name: margin
        description: round (sum (margin),2)
  - name: int_orders_operational
    columns:
      - name: orders_id
        description: primary key of the table
        tests:
              - unique
      - name: date_date
      - name: revenue
      - name: quantity
      - name: purchase_cost
      - name: margin
      - name: shipping_fee
      - name: logcost
      - name: ship_cost
        description: cast(sh.ship_cost AS FLOAT64)
      - name: operational_margin
        description: round ((margin + shipping_fee - logcost - cast(sh.ship_cost AS FLOAT64)),2)
  - name: finance_days
    columns:
      - name: date_date,
      - name: nb_transaction
        description: count (orders_id)
      - name: revenue
        description: round (sum (revenue),2)
      - name: average_basket
        description: round (SAFE_divide (sum(revenue),count (orders_id)),2)
      - name: margin
        description: round (sum(margin),2)
      - name: operational_margin
        description: round (sum (operational_margin),2)